# Generated by Django 2.1.7 on 2019-02-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenglonEgresos',
            fields=[
                ('id', models.AutoField(help_text='ID renglon de egreso', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Renglones de Egresos', max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='Estado del renglon', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIngresos',
            fields=[
                ('id', models.AutoField(help_text='ID tipo de ingreso', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripcion del tipo de Ingreso', max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='Estado del Ingreso', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(help_text='ID tipo de pago', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Tipo de Pago', max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='Estado del tipo de pago', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='tipoegresos',
            name='descripcion',
            field=models.CharField(help_text='Descripcion del tipo de Egreso', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoegresos',
            name='id',
            field=models.AutoField(help_text='ID tipo de egreso', primary_key=True, serialize=False),
        ),
    ]
