# Generated by Django 2.1.7 on 2019-02-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_auto_20190215_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionEgresos',
            fields=[
                ('id', models.AutoField(help_text='ID Gestion de Egresos', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Tipo de Pago', max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='Estado del tipo de pago', max_length=1)),
                ('renglon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.RenglonEgresos')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.TipoEgresos')),
                ('tipopago', models.ForeignKey(default='X', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.TipoPago')),
            ],
        ),
    ]
