# Generated by Django 2.1.7 on 2019-02-15 18:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.AutoField(help_text='ID Transaccion', primary_key=True, serialize=False)),
                ('tipotransaccion', models.CharField(blank=True, choices=[('I', 'Ingreso'), ('E', 'Egreso')], default='A', help_text='Tipo de Ingreso', max_length=1, verbose_name='Tipo de Ingreso')),
                ('tipo', models.CharField(blank=True, choices=[('I', 'Ingreso'), ('G', 'Gasto')], default='A', help_text='Tipo de Transaccion', max_length=1, verbose_name='Tipo de Transaccion')),
                ('fechatransaccion', models.DateField(help_text='Fecha de la transaccion', verbose_name='Fecha de la transaccion')),
                ('fecharegistro', models.DateField(default=django.utils.timezone.now, help_text='Fecha de registro', verbose_name='Fecha de registro')),
                ('monto', models.IntegerField(default=0, help_text='Monto Transaccion', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Transaccion')),
                ('notarjeta', models.CharField(help_text='Numero de tarjeta CR', max_length=100, verbose_name='Numero de tarjeta CR')),
                ('comentario', models.CharField(help_text='Comentario', max_length=100, verbose_name='Comentario')),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='Estado', max_length=1, verbose_name='Estado')),
                ('tipopago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.TipoIngresos', verbose_name='Tipo de Pago')),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='limiteegresos',
            field=models.IntegerField(default=0, help_text='Limite de Ingresos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Limite de Ingresos'),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.usuarios', verbose_name='Fuente de Ingreso'),
        ),
    ]
