# Generated by Django 2.1.7 on 2019-02-15 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_auto_20190215_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(help_text='ID Transaccion', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(help_text='Año', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Año')),
                ('mes', models.IntegerField(help_text='Mes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mes')),
                ('fechacorte', models.DateField(help_text='Fecha de Corte', verbose_name='Fecha de Corte')),
                ('balanceinicial', models.IntegerField(default=0, help_text='Balance Inicial', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance Inicial')),
                ('totalingresos', models.IntegerField(default=0, help_text='Total Ingresos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Ingresos')),
                ('totalegresos', models.IntegerField(default=0, help_text='Total Egresos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Egresos')),
                ('balancecorte', models.IntegerField(default=0, help_text='Balance Al Corte', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance Al Corte')),
            ],
        ),
    ]
